/*
 * Chomp Food Database API Documentation
 *
 * __Important:__   - An __[API key](https://chompthis.com/api/)__ is required for access to this API.   - Get yours at __[https://chompthis.com/api](https://chompthis.com/api/)__.  - -- --  __Getting Started:__   - __[Subscribe](https://chompthis.com/api/#pricing)__ to the API.   - Scroll down and click the \"__Authorize__\" button.   - Enter your API key into the \"__value__\" input, click the \"__Authorize__\" button, then click the \"__Close__\" button.   - Scroll down to the section titled \"__default__\" and click on the API endpoint you wish to use.   - Click the \"__Try it out__\" button.   - Enter the information the endpoint requires.   - Click the \"__Execute__\" button.  __Example:__    - Branded Food: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)__ API response object.   - Ingredient: __[View example](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)__ API response object.  - -- --  __How Do I Find My API Key?__   - Your API key was sent to the email address you used to create your subscription.   - You will also find your API key in the __[Client Center](https://chompthis.com/api/manage.php)__.   - _Read __[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)__ for more information._  ||| | - -- -- -- | - -- -- -- - | | [Knowledge Base](https://desk.zoho.com/portal/chompthis/kb/chomp) | [Pricing](https://chompthis.com/api/) | | [Attribution](https://chompthis.com/api/docs/attribution.php) | [Cost Calculator](https://chompthis.com/api/cost-calculator.php) | | [Terms & License](https://chompthis.com/api/terms.php) | [Database Search](https://chompthis.com/api/lookup.php) | | [Support](https://chompthis.com/api/ticket-new.php) | [Query Builder](https://chompthis.com/api/build.php) | | [Client Center](https://chompthis.com/api/manage.php) | | 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// An object containing information on an individual ingredient that was flagged as potentially not being compatible with a certain diet
    /// </summary>
    [DataContract]
    public partial class BrandedFoodObjectDietFlags : IEquatable<BrandedFoodObjectDietFlags>
    { 
        /// <summary>
        /// Ingredient name
        /// </summary>
        /// <value>Ingredient name</value>
        [DataMember(Name="ingredient")]
        public string Ingredient { get; set; }

        /// <summary>
        /// Description of the ingredient
        /// </summary>
        /// <value>Description of the ingredient</value>
        [DataMember(Name="ingredient_description")]
        public string IngredientDescription { get; set; }

        /// <summary>
        /// Name of the diet with which this ingredient may not be compatible
        /// </summary>
        /// <value>Name of the diet with which this ingredient may not be compatible</value>
        [DataMember(Name="diet_label")]
        public string DietLabel { get; set; }

        /// <summary>
        /// A description of if we believe this ingredient is compatible with the diet
        /// </summary>
        /// <value>A description of if we believe this ingredient is compatible with the diet</value>
        [DataMember(Name="is_compatible")]
        public string IsCompatible { get; set; }

        /// <summary>
        /// A numeric representation of if we believe this ingredient is compatible with the diet. Higher values indicate more compatibility
        /// </summary>
        /// <value>A numeric representation of if we believe this ingredient is compatible with the diet. Higher values indicate more compatibility</value>
        [DataMember(Name="compatibility_level")]
        public int? CompatibilityLevel { get; set; }

        /// <summary>
        /// A description of how we graded this ingredient for compatibility with the diet
        /// </summary>
        /// <value>A description of how we graded this ingredient for compatibility with the diet</value>
        [DataMember(Name="compatibility_description")]
        public string CompatibilityDescription { get; set; }

        /// <summary>
        /// Boolean representing if the ingredient is a known allergen
        /// </summary>
        /// <value>Boolean representing if the ingredient is a known allergen</value>
        [DataMember(Name="is_allergen")]
        public bool? IsAllergen { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BrandedFoodObjectDietFlags {\n");
            sb.Append("  Ingredient: ").Append(Ingredient).Append("\n");
            sb.Append("  IngredientDescription: ").Append(IngredientDescription).Append("\n");
            sb.Append("  DietLabel: ").Append(DietLabel).Append("\n");
            sb.Append("  IsCompatible: ").Append(IsCompatible).Append("\n");
            sb.Append("  CompatibilityLevel: ").Append(CompatibilityLevel).Append("\n");
            sb.Append("  CompatibilityDescription: ").Append(CompatibilityDescription).Append("\n");
            sb.Append("  IsAllergen: ").Append(IsAllergen).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BrandedFoodObjectDietFlags)obj);
        }

        /// <summary>
        /// Returns true if BrandedFoodObjectDietFlags instances are equal
        /// </summary>
        /// <param name="other">Instance of BrandedFoodObjectDietFlags to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BrandedFoodObjectDietFlags other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Ingredient == other.Ingredient ||
                    Ingredient != null &&
                    Ingredient.Equals(other.Ingredient)
                ) && 
                (
                    IngredientDescription == other.IngredientDescription ||
                    IngredientDescription != null &&
                    IngredientDescription.Equals(other.IngredientDescription)
                ) && 
                (
                    DietLabel == other.DietLabel ||
                    DietLabel != null &&
                    DietLabel.Equals(other.DietLabel)
                ) && 
                (
                    IsCompatible == other.IsCompatible ||
                    IsCompatible != null &&
                    IsCompatible.Equals(other.IsCompatible)
                ) && 
                (
                    CompatibilityLevel == other.CompatibilityLevel ||
                    CompatibilityLevel != null &&
                    CompatibilityLevel.Equals(other.CompatibilityLevel)
                ) && 
                (
                    CompatibilityDescription == other.CompatibilityDescription ||
                    CompatibilityDescription != null &&
                    CompatibilityDescription.Equals(other.CompatibilityDescription)
                ) && 
                (
                    IsAllergen == other.IsAllergen ||
                    IsAllergen != null &&
                    IsAllergen.Equals(other.IsAllergen)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Ingredient != null)
                    hashCode = hashCode * 59 + Ingredient.GetHashCode();
                    if (IngredientDescription != null)
                    hashCode = hashCode * 59 + IngredientDescription.GetHashCode();
                    if (DietLabel != null)
                    hashCode = hashCode * 59 + DietLabel.GetHashCode();
                    if (IsCompatible != null)
                    hashCode = hashCode * 59 + IsCompatible.GetHashCode();
                    if (CompatibilityLevel != null)
                    hashCode = hashCode * 59 + CompatibilityLevel.GetHashCode();
                    if (CompatibilityDescription != null)
                    hashCode = hashCode * 59 + CompatibilityDescription.GetHashCode();
                    if (IsAllergen != null)
                    hashCode = hashCode * 59 + IsAllergen.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BrandedFoodObjectDietFlags left, BrandedFoodObjectDietFlags right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BrandedFoodObjectDietFlags left, BrandedFoodObjectDietFlags right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
