/*
 * Chomp Food Database API Documentation
 *
 * ## Important An **[API key](https://chompthis.com/api/)** is required for access to this API. Get yours at **[https://chompthis.com/api](https://chompthis.com/api/)**.  ### Getting Started   * **[Subscribe](https://chompthis.com/api/#pricing)** to the API.   * Scroll down and click the \"**Authorize**\" button.   * Enter your API key into the \"**value**\" input, click the \"**Authorize**\" button, then click the \"**Close**\" button.   * Scroll down to the section titled \"**default**\" and click on the API endpoint you wish to use.   * Click the \"**Try it out**\" button.   * Enter the information the endpoint requires.   * Click the \"**Execute**\" button.  ### Example    * Branded food response object: **[View example &raquo;](https://raw.githubusercontent.com/chompfoods/examples/master/branded-food-response-object.json)**   * Ingredient response object: **[View example &raquo;](https://raw.githubusercontent.com/chompfoods/examples/master/ingredient-response-object.json)**  ### How Do I Find My API Key?   * Your API key was sent to the email address you used to create your subscription.   * You will also find your API key in the **[Client Center](https://chompthis.com/api/manage.php)**.   * Read **[this article](https://desk.zoho.com/portal/chompthis/kb/articles/how-do-i-find-my-api-key)** for more information.  ### Helpful Links   * **Help & Support**     * [Knowledge Base &raquo;](https://desk.zoho.com/portal/chompthis/kb/chomp)     * [Support &raquo;](https://chompthis.com/api/ticket-new.php)     * [Client Center &raquo;](https://chompthis.com/api/manage.php)   * **Pricing**     * [Subscription Options &raquo;](https://chompthis.com/api/)     * [Cost Calculator &raquo;](https://chompthis.com/api/cost-calculator.php)   * **Guidelines**     * [Terms & License &raquo;](https://chompthis.com/api/terms.php)     * [Attribution &raquo;](https://chompthis.com/api/docs/attribution.php) 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// An object containing the multiplication factors to be used when calculating energy from macronutrients for a specific food.
    /// </summary>
    [DataContract]
    public partial class IngredientObjectCalorieConversionFactor : IEquatable<IngredientObjectCalorieConversionFactor>
    { 
        /// <summary>
        /// The multiplication factor for protein
        /// </summary>
        /// <value>The multiplication factor for protein</value>
        [DataMember(Name="protein_value")]
        public decimal? ProteinValue { get; set; }

        /// <summary>
        /// The multiplication factor for fat
        /// </summary>
        /// <value>The multiplication factor for fat</value>
        [DataMember(Name="fat_value")]
        public decimal? FatValue { get; set; }

        /// <summary>
        /// The multiplication factor for carbohydrates
        /// </summary>
        /// <value>The multiplication factor for carbohydrates</value>
        [DataMember(Name="carbohydrate_value")]
        public decimal? CarbohydrateValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IngredientObjectCalorieConversionFactor {\n");
            sb.Append("  ProteinValue: ").Append(ProteinValue).Append("\n");
            sb.Append("  FatValue: ").Append(FatValue).Append("\n");
            sb.Append("  CarbohydrateValue: ").Append(CarbohydrateValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((IngredientObjectCalorieConversionFactor)obj);
        }

        /// <summary>
        /// Returns true if IngredientObjectCalorieConversionFactor instances are equal
        /// </summary>
        /// <param name="other">Instance of IngredientObjectCalorieConversionFactor to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IngredientObjectCalorieConversionFactor other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ProteinValue == other.ProteinValue ||
                    ProteinValue != null &&
                    ProteinValue.Equals(other.ProteinValue)
                ) && 
                (
                    FatValue == other.FatValue ||
                    FatValue != null &&
                    FatValue.Equals(other.FatValue)
                ) && 
                (
                    CarbohydrateValue == other.CarbohydrateValue ||
                    CarbohydrateValue != null &&
                    CarbohydrateValue.Equals(other.CarbohydrateValue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ProteinValue != null)
                    hashCode = hashCode * 59 + ProteinValue.GetHashCode();
                    if (FatValue != null)
                    hashCode = hashCode * 59 + FatValue.GetHashCode();
                    if (CarbohydrateValue != null)
                    hashCode = hashCode * 59 + CarbohydrateValue.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(IngredientObjectCalorieConversionFactor left, IngredientObjectCalorieConversionFactor right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(IngredientObjectCalorieConversionFactor left, IngredientObjectCalorieConversionFactor right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
